name: Java CI & Release

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Grab code
      - uses: actions/checkout@v3

      # 2. Install Java 8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'

      # 3. Build jars
      - name: Build with Maven
        run: mvn clean package --batch-mode

      # 4. Upload builded jars
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-allure-report
          path: target/*.jar

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      # 5. Dowload the artifact from the ‘build’ job
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: jmeter-allure-report
          path: target

      # 6. Create a GitHub Release and upload jar asset
      - name: Create Release and Upload JAR
        uses: softprops/action-gh-release@v1
        with:
          files: target/*.jar
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          update: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
